# This is a compose file for creating a environment of pam + ldap
# to find a alternative over sssd, which needs root
#
version: '3'
services:
  open-ldap:
    image: osixia/openldap:1.4.0
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./:/workspace
  client:
    build: .
