# This is a compose file for creating a environment of pam + ldap
# to find a alternative over sssd, which needs root
#
version: '3'
services:
  open-ldap:
    image: osixia/openldap:1.4.0
    #command:
    # - "--copy-service"
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=rootCA.pem
      - LDAP_OPENLDAP_UID=110466
      - LDAP_OPENLDAP_GID=64000
      - LDAP_SEED_INTERNAL_LDIF_PATH=/workspace/ldif
    volumes:
      - ./:/workspace
      - ./certs/:/container/service/slapd/assets/certs
  client:
    build: .
    #    entrypoint: sleep 50000
    volumes:
      - ./certs-client/:/certs
    user: appuser2
    cap_drop:
      - ALL
